// Reference tests for multiframe source structures beyond one frame per plane
// (https://github.com/QIICR/dcmqi/issues/150).
//
// Exercises the three cases the plain multiframe/mf.dcm phantom does not cover,
// using the source variants generated by util/make_multiframe_test_data.py:
//
//  1. Several source frames on the same plane (mf-2frames-per-plane.dcm):
//     every segmentation frame must reference all source frames of its plane,
//     i.e. Referenced Frame Number becomes multi-valued and, since the frames
//     are interleaved, non-contiguous ([1,4], [2,5], [3,6]).
//  2. A shared instead of per-frame Plane Position (mf-shared-plane-position.dcm):
//     only the segmentation slice on that plane gets references, and because
//     all frames of the instance apply, Referenced Frame Number must be absent
//     (a reference without frame numbers denotes the whole instance). The
//     remaining slices must carry no (empty) Derivation Image Sequence at all.
//  3. Two multiframe instances from different series referenced at once
//     (mf.dcm + mf-2frames-per-plane.dcm): each segmentation frame references
//     both instances with their own frame numbers, and the Common Instance
//     Reference module groups the instances by their actual series.
//  4. A multiframe source whose NumberOfFrames (0028,0008) is missing
//     (malformed input; the attribute is type 1 for multiframe images).
//     The are-all-frames-referenced decision must rely on the inventoried
//     per-frame items, not on (0028,0008): partial references still have to
//     carry Referenced Frame Number instead of silently claiming the whole
//     instance.
//  5. A multiframe source with more frames than a Referenced Frame Number can
//     express through the DCMTK API (> 65535). The conversion must refuse
//     rather than fall back to a reference without frame numbers, which would
//     claim every frame of the instance.
//  6. A multiframe source whose Shared Functional Groups Sequence is missing
//     or empty, which makes FGInterface reject the dataset as a whole. The
//     plane positions must then be read from the per-frame items directly, so
//     the instance still gets frame-level references instead of none at all.

#include "dcmqi/Helper.h"
#include "dcmqi/Itk2DicomConverter.h"

#include <dcmtk/dcmdata/dcdatset.h>
#include <dcmtk/dcmdata/dcdeftag.h>
#include <dcmtk/dcmdata/dcfilefo.h>
#include <dcmtk/dcmdata/dcsequen.h>

#include <itkImageFileReader.h>

#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace
{
using ImageType = itk::Image<short, 3U>;
using ReaderType = itk::ImageFileReader<ImageType>;
using Position = std::vector<double>;

const double positionTolerance = 1e-3;

#define REQUIRE(expr)                                                                  \
  do {                                                                                 \
    if (!(expr)) {                                                                     \
      std::cerr << "FAIL: " << #expr << " at " << __FILE__ << ":" << __LINE__ << std::endl; \
      return EXIT_FAILURE;                                                             \
    }                                                                                  \
  } while (0)

std::string readFile(const std::string& path)
{
  std::ifstream in(path.c_str(), std::ios::binary);
  if (!in)
  {
    std::cerr << "ERROR: cannot open " << path << std::endl;
    return std::string();
  }
  std::ostringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

// Image Position (Patient) of the PlanePositionSequence in the given functional
// group item, empty if absent.
Position planePosition(DcmItem* fgItem)
{
  Position result;
  DcmItem* planePosItem = nullptr;
  if (!fgItem
      || fgItem->findAndGetSequenceItem(DCM_PlanePositionSequence, planePosItem, 0).bad()
      || !planePosItem)
  {
    return result;
  }
  for (int j = 0; j < 3; ++j)
  {
    OFString value;
    if (planePosItem->findAndGetOFString(DCM_ImagePositionPatient, value, j).bad())
    {
      return Position();
    }
    result.push_back(atof(value.c_str()));
  }
  return result;
}

bool samePosition(const Position& a, const Position& b)
{
  if ((a.size() != 3) || (b.size() != 3))
  {
    return false;
  }
  for (int j = 0; j < 3; ++j)
  {
    if (std::fabs(a[j] - b[j]) > positionTolerance)
    {
      return false;
    }
  }
  return true;
}

// Per-frame plane positions of a multiframe source, falling back to the shared
// functional groups for sources that share one position across all frames.
struct SourceInfo
{
  OFString sopInstanceUID;
  OFString seriesInstanceUID;
  size_t numberOfFrames;
  std::vector<Position> framePositions; // index 0 == frame number 1
};

bool readSourceInfo(const std::string& path, SourceInfo& info)
{
  DcmFileFormat ff;
  if (ff.loadFile(path.c_str()).bad())
  {
    std::cerr << "ERROR: cannot read " << path << std::endl;
    return false;
  }
  DcmDataset* ds = ff.getDataset();
  if (ds->findAndGetOFString(DCM_SOPInstanceUID, info.sopInstanceUID).bad()
      || ds->findAndGetOFString(DCM_SeriesInstanceUID, info.seriesInstanceUID).bad())
  {
    return false;
  }

  Position sharedPosition;
  DcmItem* sharedItem = nullptr;
  if (ds->findAndGetSequenceItem(DCM_SharedFunctionalGroupsSequence, sharedItem, 0).good() && sharedItem)
  {
    sharedPosition = planePosition(sharedItem);
  }

  DcmSequenceOfItems* perFrameSeq = nullptr;
  if (ds->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, perFrameSeq).bad() || !perFrameSeq)
  {
    return false;
  }
  for (unsigned long f = 0; f < perFrameSeq->card(); ++f)
  {
    Position position = planePosition(perFrameSeq->getItem(f));
    info.framePositions.push_back(position.empty() ? sharedPosition : position);
  }
  info.numberOfFrames = info.framePositions.size();
  return info.numberOfFrames > 0;
}

// Frame numbers (1-based) of the source frames located on the given plane
std::set<Uint32> framesOnPlane(const SourceInfo& info, const Position& plane)
{
  std::set<Uint32> result;
  for (size_t f = 0; f < info.framePositions.size(); ++f)
  {
    if (samePosition(info.framePositions[f], plane))
    {
      result.insert(static_cast<Uint32>(f + 1));
    }
  }
  return result;
}

// Referenced Frame Numbers of a Source Image Sequence item; empty if the
// attribute is absent (which denotes the whole instance)
std::set<Uint32> referencedFrameNumbers(DcmItem* sourceImageItem)
{
  std::set<Uint32> result;
  DcmElement* element = nullptr;
  if (sourceImageItem->findAndGetElement(DCM_ReferencedFrameNumber, element).bad() || !element)
  {
    return result;
  }
  for (unsigned long i = 0; i < element->getVM(); ++i)
  {
    OFString value;
    if (element->getOFString(value, i).good())
    {
      result.insert(static_cast<Uint32>(atoi(value.c_str())));
    }
  }
  return result;
}

std::unique_ptr<DcmDataset> convert(const std::vector<std::string>& sourceFiles,
                                    const std::vector<ImageType::ConstPointer>& segmentations,
                                    const std::string& metadata)
{
  std::vector<DcmItem*> datasets = dcmqi::Helper::loadDatasets(sourceFiles);
  std::unique_ptr<DcmDataset> result(
      dcmqi::Itk2DicomConverter::itkimage2dcmSegmentation(datasets, segmentations, metadata,
                                                          false /* skipEmptySlices */));
  for (DcmItem* item : datasets) { delete item; }
  return result;
}

// Variant taking datasets that were already loaded (and possibly modified)
std::unique_ptr<DcmDataset> convertDatasets(std::vector<DcmItem*>& datasets,
                                            const std::vector<ImageType::ConstPointer>& segmentations,
                                            const std::string& metadata)
{
  return std::unique_ptr<DcmDataset>(
      dcmqi::Itk2DicomConverter::itkimage2dcmSegmentation(datasets, segmentations, metadata,
                                                          false /* skipEmptySlices */));
}

// For every frame of the segmentation, check the references against the source
// frames actually located on the frame's plane.
int checkFrameReferences(DcmDataset* seg, const std::vector<SourceInfo>& sources)
{
  DcmSequenceOfItems* perFrameSeq = nullptr;
  REQUIRE(seg->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, perFrameSeq).good() && perFrameSeq);

  for (unsigned long f = 0; f < perFrameSeq->card(); ++f)
  {
    DcmItem* fgItem = perFrameSeq->getItem(f);
    const Position segPlane = planePosition(fgItem);
    REQUIRE(segPlane.size() == 3);

    // which sources contribute frames to this plane?
    std::map<OFString, std::set<Uint32> > expected;
    for (const SourceInfo& source : sources)
    {
      std::set<Uint32> frames = framesOnPlane(source, segPlane);
      if (!frames.empty())
      {
        expected[source.sopInstanceUID] = frames;
      }
    }

    DcmItem* derivationItem = nullptr;
    const bool hasDerivation =
        fgItem->findAndGetSequenceItem(DCM_DerivationImageSequence, derivationItem, 0).good() && derivationItem;

    if (expected.empty())
    {
      // no source frame on this plane: there must be no (empty) derivation FG
      REQUIRE(!hasDerivation);
      continue;
    }
    REQUIRE(hasDerivation);

    DcmSequenceOfItems* sourceImageSeq = nullptr;
    REQUIRE(derivationItem->findAndGetSequence(DCM_SourceImageSequence, sourceImageSeq).good() && sourceImageSeq);
    REQUIRE(sourceImageSeq->card() == expected.size());

    for (unsigned long s = 0; s < sourceImageSeq->card(); ++s)
    {
      DcmItem* sourceImageItem = sourceImageSeq->getItem(s);
      OFString uid;
      REQUIRE(sourceImageItem->findAndGetOFString(DCM_ReferencedSOPInstanceUID, uid).good());
      REQUIRE(expected.find(uid) != expected.end());

      const SourceInfo* source = nullptr;
      for (const SourceInfo& candidate : sources)
      {
        if (candidate.sopInstanceUID == uid) { source = &candidate; }
      }
      REQUIRE(source != nullptr);

      const std::set<Uint32> referenced = referencedFrameNumbers(sourceImageItem);
      if (referenced.empty())
      {
        // whole instance referenced: only valid if all its frames apply
        REQUIRE(expected[uid].size() == source->numberOfFrames);
      }
      else
      {
        REQUIRE(referenced == expected[uid]);
      }
    }
  }
  return EXIT_SUCCESS;
}
}

int main(int argc, char* argv[])
{
  if (argc != 6)
  {
    std::cerr << "Usage: " << argv[0]
              << " <metadata.json> <segmentation.nrrd> <mf.dcm>"
              << " <mf-2frames-per-plane.dcm> <mf-shared-plane-position.dcm>" << std::endl;
    return EXIT_FAILURE;
  }

  const std::string metadata = readFile(argv[1]);
  REQUIRE(!metadata.empty());

  const std::string plainFile = argv[3];
  const std::string twoPerPlaneFile = argv[4];
  const std::string sharedPositionFile = argv[5];

  SourceInfo plain, twoPerPlane, sharedPosition;
  REQUIRE(readSourceInfo(plainFile, plain));
  REQUIRE(readSourceInfo(twoPerPlaneFile, twoPerPlane));
  REQUIRE(readSourceInfo(sharedPositionFile, sharedPosition));
  REQUIRE(twoPerPlane.numberOfFrames == 2 * plain.numberOfFrames);
  REQUIRE(plain.seriesInstanceUID != twoPerPlane.seriesInstanceUID);

  ReaderType::Pointer reader = ReaderType::New();
  reader->SetFileName(argv[2]);
  try
  {
    reader->Update();
  }
  catch (const itk::ExceptionObject& e)
  {
    std::cerr << "ERROR: failed to load segmentation: " << e.what() << std::endl;
    return EXIT_FAILURE;
  }
  std::vector<ImageType::ConstPointer> segmentations;
  segmentations.emplace_back(reader->GetOutput());

  // 1. several source frames per plane -> multi-valued Referenced Frame Number
  {
    std::unique_ptr<DcmDataset> seg(convert({twoPerPlaneFile}, segmentations, metadata));
    REQUIRE(seg != nullptr);
    REQUIRE(checkFrameReferences(seg.get(), {twoPerPlane}) == EXIT_SUCCESS);

    // the interleaved acquisitions must produce non-contiguous frame numbers
    DcmItem* fgItem = nullptr;
    REQUIRE(seg->findAndGetSequenceItem(DCM_PerFrameFunctionalGroupsSequence, fgItem, 0).good() && fgItem);
    DcmItem* derivationItem = nullptr;
    REQUIRE(fgItem->findAndGetSequenceItem(DCM_DerivationImageSequence, derivationItem, 0).good() && derivationItem);
    DcmItem* sourceImageItem = nullptr;
    REQUIRE(derivationItem->findAndGetSequenceItem(DCM_SourceImageSequence, sourceImageItem, 0).good() && sourceImageItem);
    const std::set<Uint32> frames = referencedFrameNumbers(sourceImageItem);
    REQUIRE(frames.size() == 2);
    REQUIRE(*frames.begin() == 1 && *frames.rbegin() == 1 + plain.numberOfFrames);
  }

  // 2. shared plane position -> whole-instance reference on one slice only
  {
    std::unique_ptr<DcmDataset> seg(convert({sharedPositionFile}, segmentations, metadata));
    REQUIRE(seg != nullptr);
    REQUIRE(checkFrameReferences(seg.get(), {sharedPosition}) == EXIT_SUCCESS);

    // exactly one frame may carry references, and without frame numbers
    DcmSequenceOfItems* perFrameSeq = nullptr;
    REQUIRE(seg->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, perFrameSeq).good() && perFrameSeq);
    unsigned long framesWithReferences = 0;
    for (unsigned long f = 0; f < perFrameSeq->card(); ++f)
    {
      DcmItem* derivationItem = nullptr;
      if (perFrameSeq->getItem(f)->findAndGetSequenceItem(DCM_DerivationImageSequence, derivationItem, 0).good()
          && derivationItem)
      {
        framesWithReferences++;
        DcmItem* sourceImageItem = nullptr;
        REQUIRE(derivationItem->findAndGetSequenceItem(DCM_SourceImageSequence, sourceImageItem, 0).good() && sourceImageItem);
        REQUIRE(!sourceImageItem->tagExists(DCM_ReferencedFrameNumber));
      }
    }
    REQUIRE(framesWithReferences == 1);
  }

  // 3. two multiframe instances from different series
  {
    std::unique_ptr<DcmDataset> seg(convert({plainFile, twoPerPlaneFile}, segmentations, metadata));
    REQUIRE(seg != nullptr);
    REQUIRE(checkFrameReferences(seg.get(), {plain, twoPerPlane}) == EXIT_SUCCESS);

    // both series must appear in the Common Instance Reference module, each
    // with its own instance
    DcmSequenceOfItems* refSeriesSeq = nullptr;
    REQUIRE(seg->findAndGetSequence(DCM_ReferencedSeriesSequence, refSeriesSeq).good() && refSeriesSeq);
    REQUIRE(refSeriesSeq->card() == 2);
    std::set<OFString> seriesUIDs, instanceUIDs;
    for (unsigned long s = 0; s < refSeriesSeq->card(); ++s)
    {
      OFString seriesUID;
      REQUIRE(refSeriesSeq->getItem(s)->findAndGetOFString(DCM_SeriesInstanceUID, seriesUID).good());
      seriesUIDs.insert(seriesUID);
      DcmSequenceOfItems* refInstanceSeq = nullptr;
      REQUIRE(refSeriesSeq->getItem(s)->findAndGetSequence(DCM_ReferencedInstanceSequence, refInstanceSeq).good() && refInstanceSeq);
      REQUIRE(refInstanceSeq->card() == 1);
      OFString instanceUID;
      REQUIRE(refInstanceSeq->getItem(0)->findAndGetOFString(DCM_ReferencedSOPInstanceUID, instanceUID).good());
      instanceUIDs.insert(instanceUID);
    }
    REQUIRE(seriesUIDs == (std::set<OFString>{plain.seriesInstanceUID, twoPerPlane.seriesInstanceUID}));
    REQUIRE(instanceUIDs == (std::set<OFString>{plain.sopInstanceUID, twoPerPlane.sopInstanceUID}));
  }

  // 4. missing NumberOfFrames: partial references must still carry frame
  //    numbers (regression test for deciding completeness against
  //    (0028,0008) instead of the inventoried frames)
  {
    std::vector<DcmItem*> datasets = dcmqi::Helper::loadDatasets({twoPerPlaneFile});
    REQUIRE(datasets.size() == 1);
    REQUIRE(datasets[0]->findAndDeleteElement(DCM_NumberOfFrames).good());

    std::unique_ptr<DcmDataset> seg(convertDatasets(datasets, segmentations, metadata));
    REQUIRE(seg != nullptr);
    // every frame references two of the six source frames, so Referenced
    // Frame Number is required on every source image item
    REQUIRE(checkFrameReferences(seg.get(), {twoPerPlane}) == EXIT_SUCCESS);
    DcmSequenceOfItems* perFrameSeq = nullptr;
    REQUIRE(seg->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, perFrameSeq).good() && perFrameSeq);
    for (unsigned long f = 0; f < perFrameSeq->card(); ++f)
    {
      DcmItem* derivationItem = nullptr;
      REQUIRE(perFrameSeq->getItem(f)->findAndGetSequenceItem(DCM_DerivationImageSequence, derivationItem, 0).good()
              && derivationItem);
      DcmItem* sourceImageItem = nullptr;
      REQUIRE(derivationItem->findAndGetSequenceItem(DCM_SourceImageSequence, sourceImageItem, 0).good()
              && sourceImageItem);
      REQUIRE(referencedFrameNumbers(sourceImageItem).size() == 2);
    }
    for (DcmItem* item : datasets) { delete item; }
  }

  // 5. more frames than Referenced Frame Number can express: refuse instead
  //    of silently referencing the whole instance
  {
    std::vector<DcmItem*> datasets = dcmqi::Helper::loadDatasets({plainFile});
    REQUIRE(datasets.size() == 1);
    DcmSequenceOfItems* origSeq = nullptr;
    REQUIRE(datasets[0]->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, origSeq).good() && origSeq);

    // Push the real frames past frame number 65535 by prepending filler items.
    // They carry no Plane Position, so they stay unmapped; only the real
    // frames are referenced, and their numbers now exceed the limit.
    const unsigned long filler = 65536;
    std::unique_ptr<DcmSequenceOfItems> bigSeq(new DcmSequenceOfItems(DCM_PerFrameFunctionalGroupsSequence));
    for (unsigned long i = 0; i < filler; ++i)
    {
      REQUIRE(bigSeq->insert(new DcmItem()).good());
    }
    for (unsigned long i = 0; i < origSeq->card(); ++i)
    {
      REQUIRE(bigSeq->insert(new DcmItem(*origSeq->getItem(i))).good());
    }
    REQUIRE(datasets[0]->insert(bigSeq.release(), OFTrue /* replace */).good());

    bool refused = false;
    try
    {
      std::unique_ptr<DcmDataset> seg(convertDatasets(datasets, segmentations, metadata));
      refused = (seg == nullptr);
    }
    catch (...)   // the converter reports failing conditions by throwing
    {
      refused = true;
    }
    REQUIRE(refused);
    for (DcmItem* item : datasets) { delete item; }
  }

  // 6. unparsable functional groups: the plane positions must still be found
  for (int variant = 0; variant < 2; ++variant)
  {
    std::vector<DcmItem*> datasets = dcmqi::Helper::loadDatasets({plainFile});
    REQUIRE(datasets.size() == 1);
    if (variant == 0)
    {
      // Shared Functional Groups Sequence missing entirely
      REQUIRE(datasets[0]->findAndDeleteElement(DCM_SharedFunctionalGroupsSequence).good());
    }
    else
    {
      // present but empty, which FGInterface rejects just the same
      DcmSequenceOfItems* sharedSeq = nullptr;
      REQUIRE(datasets[0]->findAndGetSequence(DCM_SharedFunctionalGroupsSequence, sharedSeq).good() && sharedSeq);
      sharedSeq->clear();
    }

    std::unique_ptr<DcmDataset> seg(convertDatasets(datasets, segmentations, metadata));
    REQUIRE(seg != nullptr);
    // same references as with the intact file: the frame positions are
    // unchanged, only the way they have to be read differs
    REQUIRE(checkFrameReferences(seg.get(), {plain}) == EXIT_SUCCESS);
    unsigned long framesWithReferences = 0;
    DcmSequenceOfItems* perFrameSeq = nullptr;
    REQUIRE(seg->findAndGetSequence(DCM_PerFrameFunctionalGroupsSequence, perFrameSeq).good() && perFrameSeq);
    for (unsigned long f = 0; f < perFrameSeq->card(); ++f)
    {
      DcmItem* derivationItem = nullptr;
      if (perFrameSeq->getItem(f)->findAndGetSequenceItem(DCM_DerivationImageSequence, derivationItem, 0).good()
          && derivationItem)
      {
        framesWithReferences++;
      }
    }
    REQUIRE(framesWithReferences == perFrameSeq->card());
    for (DcmItem* item : datasets) { delete item; }
  }

  std::cout << "PASS: multiframe sources with several frames per plane, with a shared plane "
            << "position, from two series, with a missing NumberOfFrames attribute, beyond "
            << "the expressible frame number, and without parsable functional groups are "
            << "handled correctly." << std::endl;
  return EXIT_SUCCESS;
}
