@startuml

class SegmentAttributes {
- labelID : unsigned
- attributesDictionary : map<string, string>
+ setLabelID(unsigned labelID) : void
+ lookupAttribute(string key) : string
+ populateAttributesFromString(string attributesStr) : int
+ PrintSelf() : void
}

@enduml