name: C/C++ CI Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17'
          msbuild-architecture: x64

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.0'

      - name: Install prerequisite python packages
        run: |
          pip install jsondiff

      - name: Configure project

        run: |
          ls ${{ github.workspace }}
          echo "WORKSPACE dir: ${{ github.workspace }}"
          cmake --version
          mkdir ${{ github.workspace }}\b
          echo "Step 2"
          cd ${{ github.workspace }}\b
          echo "Step 3"
          cmake -G "Visual Studio 17 2022" -Ax64 -DBUILD_SHARED_LIBS:BOOL=OFF ${{ github.workspace }}

      - name: Build dcmqi
        run: |
          cd ${{ github.workspace }}\b/
          cmake --build . --config Release -- /m

      - name: Test dcmqi
        run: |
          cd ${{ github.workspace }}\b\dcmqi-build
          ctest -VV -C Release -D ExperimentalTest --no-compress-output

      - name: Package dcmqi
        run: |
          cd ${{ github.workspace }}\b\dcmqi-build
          cmake --build . --config Release --target PACKAGE -- /m

      - uses: actions/upload-artifact@v4
        with:
            name: dcmqi-build
            path: ${{ github.workspace }}\b\dcmqi-build\dcmqi-*-win64*.zip

  publish-windows:

    runs-on: windows-2022
    timeout-minutes: 5
    # Only run if the event is not a pull request and the repository owner is QIICR.
    # The latter is to prevent forks from publishing packages even if the owner's token
    # would have sufficient privileges.
    if: ${{ (github.event_name != 'pull_request') && (github.repository_owner == 'QIICR')}}

    needs: build-windows

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - uses: actions/download-artifact@v4
        with:
          name: dcmqi-build
          path: ${{ github.workspace }}\b\dcmqi-build

      - name: Publish package
        run: |
          pip install -U "scikit-ci-addons>=0.22.0"
          ci_addons publish_github_release qiicr/dcmqi `
          --exit-success-if-missing-token `
          --release-packages "${{ github.workspace }}\b\dcmqi-build\dcmqi-*-win64.zip" `
          --prerelease-packages "${{ github.workspace }}\b\dcmqi-build\dcmqi-*-win64-*.zip" `
          --prerelease-packages-clear-pattern "dcmqi-*-win64-*" `
          --prerelease-packages-keep-pattern "*<COMMIT_DATE>-<COMMIT_SHORT_SHA>*" `
          --token ${{ secrets.GA_TOKEN }}
